### ISSUE TITLE
Feature request: Make use of `engine` for property mappedness check in query builder 

### ISSUE THREAD

**Issue by akphi** [finos/legend-studio#1069]
### Similar requests

- [X] I have searched and found no existing similar requests

### What problems are you trying to solve?

The current algorithm mused to check for _mapped-ness_ of properties in query builder is error-prone. We maintain it without handling certain complexities such as:
- operation mapping
- embedded mapping
- association mapping
- service stores
- derived properties

We should in fact rely on engine to do this analytics for us instead.

### Describe the solution you would like to see implemented

- [x] `engine` Expose the endpoint in engine - https://github.com/finos/legend-engine/pull/740
- [x] `engine` Make sure we incorporate the current check that we have in `Studio` and more, account for cases mentioned above:
  - [x] Operation mapping (with different operations)
  - [x] Embedded mapping
  - [x] Association and association mapping
  - [x] Service Stores
  - [x] Derived properties
  - [ ] Also take care of https://github.com/finos/legend-studio/issues/834
  - [ ] Also take care of https://github.com/finos/legend-studio/issues/816
  - [ ] Check the intersection between this and https://github.com/finos/legend-studio/issues/1172
- [ ] Remove the code for mappedness check in query builder and wire it up with engine - https://github.com/finos/legend-studio/pull/1186
- [x] Come back and check https://github.com/finos/legend-studio/issues/927

### Contribution

- [ ] I would like to work on this feature

**Comment by YannanGao-gs** [comment]
model 


```
###Relational
Database model::Test
(
  Table FirmTable
  (
    id INTEGER PRIMARY KEY,
    Legal_name VARCHAR(200)
  )
  Table PersonTable
  (
    id INTEGER PRIMARY KEY,
    firm_id INTEGER,
    firstName VARCHAR(200),
    lastName VARCHAR(200)
  )
  Table AddressTable
  (
    id INTEGER PRIMARY KEY,
    firm_id INTEGER,
    name VARCHAR(200)
  )

  Join FirmPerson(PersonTable.firm_id = FirmTable.id)
)


###Pure

Class model::LegalEntity
{
  employees: model::Person[1..*];
}

Class  model::Firm extends model::LegalEntity
{
  legalName: String[1];
}

Class model::Person
{
  firstName: String[1];
  lastName: String[1];
  firms: model::Firm[1..*];
}

###Mapping
Mapping model::NewMapping
(
  *model::Firm: Relational
  {
    ~primaryKey
    (
      [model::Test]FirmTable.id
    )
    ~mainTable [model::Test]FirmTable
    employees[model_Person]: [model::Test]@FirmPerson
  }
  *model::Person: Relational
  {
    ~primaryKey
    (
      [model::Test]PersonTable.id
    )
    ~mainTable [model::Test]PersonTable
    firstName: [model::Test]PersonTable.firstName,
    lastName: [model::Test]PersonTable.lastName,
    firms[model_Firm]: [model::Test]@FirmPerson
  }
  *model::LegalEntity: Operation
  {
    meta::pure::router::operations::inheritance_OperationSetImplementation_1__SetImplementation_MANY_()
  }
)
```

**Comment by akphi** [comment]
Let's remember to come back and check all the items of this PR when we're done with https://github.com/finos/legend-studio/pull/1186
