### ISSUE TITLE
Support Testable flow Phase 1

### ISSUE THREAD

**Issue by gayathrir11** [finos/legend-studio#1077]
### Goal

Support `testable` flow in studio including test mode and revamping of service and mapping tests editors. 

### Problem
We want to address the inconsistency of writing service and mapping tests as well as writing test data.
Additionally it is not very intuitive to create service tests today. To address this we will  move from a `Lambda` based assertion to specific type of assertions such as EqualToJSON etc.
Additionally the introduction of `DataElement` will allow to more intuitive create test data and share data across multiple tests. 
Furthermore when executing test via studio the new apis will give more context to better debug failing tests such as execution result etc. 

### Phase 1: Graph and basic editor support
- ability to define following testables with the following test types and embedded data types in text mode
- ability to run the relevant tests through the global test runner (Legacy Test will not be supported via this mode) -> https://github.com/finos/legend-studio/issues/865. 
- Testables will run as part of the projects pipeline flow
- ensure both flows use the testable test runners in engine. Studio should not use them to run
- Testables to Support: `Service`, `Mapping`
- Assert Types: `EqualTo`, `EqualToJSON`, `EqualToTDS`
- Embedded Data: `Relational`, `ServiceStore` , `ExternalFormat` `ModelStore`
 
### Phase 2: Advanced editor support (to be moved to a separate issue)
- Service Testable Editor 
- Mapping Testable Editor
- Editors for the following Embedded Data Types: `Relational`, `ServiceStore` and `ExternalFormat`
- Enhance form support for the embedded data type editors by allowing users to specify the store while creating the data element and auto populate the properties for embedded data

### Phase 3: Migration Plan from Legacy (to be moved to a separate issue)
_TBD_

## Implementation
In order to fully support the new testable flow we must ensure the following 
- [ ] [pure](https://github.com/finos/legend-pure)/[engine](https://github.com/finos/legend-engine) Current testable elements tests are updated to the new testable framework
  - [ ] `Mapping` @gs-gunjan 
  - [x] `Service` @hardikmaheshwari  
- [ ]  [pure](https://github.com/finos/legend-pure)/[engine](https://github.com/finos/legend-engine) `DataElements` are updated to support the follow embedded data
    - [x] `ServiceStore` @hardikmaheshwari 
    - [ ] `FlatData` - need to add a test to ensure we can migrate flat data tests to the new testable flow
    - [ ] `Relational` @MauricioUyaguari
      - [x] Add Relational Data Compiler, Grammar, Studio
      - [x] Add `equalToTDS` Compiler,Grammar, Studio
      - [x] Relational should work with equalToJSON as well
      - [ ]  Ensure `equalToTDS` tests run with api
      - [ ] `Investigate` relational queries that return graph fetch break while running tests. (feeling its because the return type is complex [firm with person properties]
    - [x] `ExternalFormat` @hardikmaheshwari 
    - [x] `ModelStore` @hardikmaheshwari 
- [ ] [engine](https://github.com/finos/legend-engine) Ensure testable elements `tests` are run as part of run testable apis
  - [ ] `Mapping` @gs-gunjan 
  - [x] `Service` @hardikmaheshwari 
- [ ] [sdlc](https://github.com/finos/legend-sdlc) Ensure testable elements `tests` are run in sdlc pipeline @hardikmaheshwari 
- [ ] Support `DataElement` in text mode
    - [x] `ServiceStore` ( https://github.com/finos/legend-studio/issues/1078) 
    - [x] `Relational` 
    - [ ] `Flatdata`, still need ? 
    - [x] `ExternalFormat`  
    - [x] `ModelStore` 
- [ ] Support Testable `tests` in text mode
  - [ ] `Mapping` 
  - [x] `Service` 
 - [ ] Support `DataElement` in form mode
    - [x] `ServiceStore` 
    - [ ] `Relational` 
    - [x] `ExternalFormat`  #1133 
    - [ ] `ModelStore` 
- [x] Support executing Testable
- [x] Rework Service Test Editor
- [ ] Rework Mapping Test Editor
- [ ] Figure out Strategy for dealing with legacy tests. i.e transform them to new, read but not write. etc. 
- [x] V0 of global test runner 
  - [x] Add panel of global test runner
  - [x] run tests for all testables 

### Concerns/To Check
- [ ] should `RelationalTestData` support sql statements as input
- [ ] Base 64 Encoding of TestData to avoid escape hacks

### Data Element Model
![image](https://user-images.githubusercontent.com/29690824/164786263-570ea2e0-76a9-4486-bf2b-f631a31c2126.png)

### Test and Test Result Model
![image](https://user-images.githubusercontent.com/29690824/164786326-04860c78-572e-4442-9885-e77db202a1fa.png)

### Relevant PRS:
- [ ] https://github.com/finos/legend-pure/pull/544
- [ ] https://github.com/finos/legend-pure/pull/533
- [x] https://github.com/finos/legend-pure/pull/521
- [ ] https://github.com/finos/legend-engine/pull/658
- [x] https://github.com/finos/legend-engine/pull/631
- [x] https://github.com/finos/legend-sdlc/pull/418
- [x] https://github.com/finos/legend-studio/pull/1114

### WIP

Relational Test Grammar
```
###Data
Data my::RelationalData
{
  Relational
  #{
    PersonTable:
      {
        columns:
        [
          'id',
          'firstName',
          'lastName'
        ];
        rows:
        [
          '1,Mauricio,Uyaguari',
          '2,An,Phi'
        ];
      }
  }#
}


###Service
Service model::MyService
{
  pattern: '/d2c48a9c-70fa-46e3-8173-c355e774004f';
  documentation: '';
  autoActivateUpdates: true;
  execution: Single
  {
    query: |model::Person.all()->project([x|$x.firstName, x|$x.lastName], ['First Name', 'Last Name']);
    mapping: mapping::RelationalMapping;
    runtime: model::Runtime;
  }
  testSuites:
  [
    testSuite1:
    {
      data:
      [
        connections:
        [
          connection_1:
            Reference
            #{
              my::RelationalData
            }#
        ]
      ]
      tests:
      [
        test1:
        {
          asserts:
          [
            assert1:
              EqualToTDS
              #{
                expected : 
                  {
                    columns: 
                    [
                      'firstName',
                      'lastName'
                    ];
                    rows:
                    [
                      '1,Mauricio,Uyaguari',
                      '2,An,Phi'
                    ];
                  };
              }#
          ]
        }
      ]
    }
  ]
  test: Single
  {
    data: 'default\nPersonTable\nid,firstName,lastName\n1,John,Doe\n2,An,Phi\n3,Mauricio,Uyaguari\n-----\n';
    asserts:
    [
      { [], res: meta::pure::mapping::Result[1]|$res.values->cast(@TabularDataSet)->toOne().rows->map(r|$r.values->makeString(',')) == ['John,Doe', 'An,Phi', 'Mauricio,Uyaguari'] }
    ];
  }
}


###Relational
Database store::TestDB
(
  Table PersonTable
  (
    id INTEGER PRIMARY KEY,
    firm_id INTEGER,
    firstName VARCHAR(200),
    lastName VARCHAR(200)
  )
)


###Pure
Class model::Person
{
  firstName: String[1];
  lastName: String[1];
}


###Mapping
Mapping mapping::RelationalMapping
(
  *model::Person: Relational
  {
    ~primaryKey
    (
      [store::TestDB]PersonTable.id
    )
    ~mainTable [store::TestDB]PersonTable
    firstName: [store::TestDB]PersonTable.firstName,
    lastName: [store::TestDB]PersonTable.lastName
  }

  MappingTests
  [
    test_csv
    (
      query: |model::Person.all()->project([x|$x.firstName, x|$x.lastName], ['First Name', 'Last Name']);
      data:
      [
        <Relational, CSV, store::TestDB, 
          'default\n'+
          'PersonTable\n'+
          'id,firstName,lastName\n'+
          '1,Mauricio,Uyaguari\n'+
          '2,An,Phi\n'+
          '\n\n\n'
        >
      ];
      assert: '[{"values":["Mauricio","Uyaguari"]},{"values":["An","Phi"]}]';
    )
  ]
)


###Connection
RelationalDatabaseConnection model::MyConnection
{
  store: store::TestDB;
  type: H2;
  specification: LocalH2
  {
    testDataSetupSqls: [
      'Drop table if exists FirmTable;\nDrop table if exists PersonTable;\nCreate Table FirmTable(id INT, Legal_Name VARCHAR(200));\nCreate Table PersonTable(id INT, firm_id INT, lastName VARCHAR(200), firstName VARCHAR(200));\nInsert into FirmTable (id, Legal_Name) values (1, \'FirmA\');\nInsert into FirmTable (id, Legal_Name) values (2, \'Apple\');\nInsert into PersonTable (id, firm_id, lastName, firstName) values (1, 1, \'John\', \'Doe\');\nInsert into PersonTable (id, firm_id, lastName, firstName) values (2, 2, \'Tim\', \'Smith\');\nInsert into PersonTable (id, firm_id, lastName, firstName) values (3, 3, \'Nicole\', \'Doe\');\n\n'
      ];
  };
  auth: DefaultH2;
}


###Runtime
Runtime model::Runtime
{
  mappings:
  [
    mapping::RelationalMapping
  ];
  connections:
  [
    store::TestDB:
    [
      connection_1: model::MyConnection
    ]
  ];
}

```

**Comment by hardikmaheshwari** [comment]
@MauricioUyaguari I believe we don't need to support FlatData at the same level as stores/external format. FlatData is 1 type of ExternalFormat and that's the direction we are planning to take from engine perspective. 
So I guess we don't need explicit steps for flatData. It was added as part of ExternalFormat support.
Let me know if this makes sense

**Comment by hardikmaheshwari** [comment]
@MauricioUyaguari We should not need any additional work to run mapping tests (when uplifted to testable) other than https://github.com/finos/legend-sdlc/pull/418, changes in this PR should run tests for all testables (service, mapping, persistence, etc) as long as implementation of [TestableRunnerExtension](https://github.com/finos/legend-engine/blob/master/legend-engine-testable/src/main/java/org/finos/legend/engine/testable/extension/TestableRunnerExtension.java) for those are provided in engine

**Comment by MauricioUyaguari** [comment]
> @MauricioUyaguari so phase 1 - global test runner won't run legacy test right?
Global Test Runner will only run Testable tests. No legacy tests will there.

**Comment by MauricioUyaguari** [comment]
Current Service M2M Grammar . 
@hardikmaheshwari @gs-gunjan do we see potential consistency issues with the current service test grammars ? 
```
###Service
Service mapping::ModelToModelMappingService2
{
  pattern: '/5a17dd83-825c-42cf-84ce-e016f306933e';
  documentation: '';
  autoActivateUpdates: true;
  execution: Single
  {
    query: |model::target::_Firm.all()->graphFetchChecked(#{model::target::_Firm{name,type,employees{fullName}}}#)->serialize(#{model::target::_Firm{name,type,employees{fullName}}}#);
    mapping: mapping::ModelToModelMapping;
    runtime:
    #{
      mappings:
      [
        mapping::ModelToModelMapping
      ];
      connections:
      [
        ModelStore:
        [
          connection_1:
          #{
            JsonModelConnection
            {
              class: model::Firm;
              url: 'data:application/json,%7B%22employees%22%3A%5B%7B%22firstName%22%3A%22firstName%2019%22%2C%22lastName%22%3A%22lastName%209%22%7D%5D%2C%22legalName%22%3A%22legalName%2072%22%2C%22type%22%3A%22llc%22%7D';
            }
          }#
        ]
      ];
    }#;
  }
  testSuites:
  [
    testSuite_1:
    {
      data:
      [
        connections:
        [
          connection_1:
            ExternalFormat
            #{
              contentType: 'application/json';
              data: '{\n  "employees": [\n    {\n      "firstName": "firstName 19",\n      "lastName": "lastName 9"\n    }\n  ],\n  "legalName": "legalName 72",\n  "type": "llc"\n}';
            }#
        ]
      ]
      tests:
      [
        test_1:
        {
          asserts:
          [
            assertion_1:
              EqualToJson
              #{
                expected : 
                  ExternalFormat
                  #{
                    contentType: 'application/json';
                    data: '{\n  "defects" : [ ],\n  "source" : {\n    "defects" : [ ],\n    "source" : {\n      "number" : 2,\n      "record" : "{\\"employees\\":[{\\"firstName\\":\\"firstName 19\\",\\"lastName\\":\\"lastName 9\\"}],\\"legalName\\":\\"legalName 72\\",\\"type\\":\\"llc\\"}"\n    },\n    "value" : {\n      "employees" : [ {\n        "firstName" : "firstName 19",\n        "lastName" : "lastName 9"\n      } ],\n      "legalName" : "legalName 72",\n      "type" : "llc"\n    }\n  },\n  "value" : {\n    "name" : "legalName 72",\n    "type" : "LLC",\n    "employees" : [ {\n      "fullName" : "firstName 19 lastName 9"\n    } ]\n  }\n}';
                  }#;
              }#
          ]
        }
      ]
    }
  ]
}
```

**Comment by hardikmaheshwari** [comment]
> Current Service M2M Grammar . @hardikmaheshwari @gs-gunjan do we see potential consistency issues with the current service test grammars ?
> 
> ```
> ###Service
> Service mapping::ModelToModelMappingService2
> {
>   pattern: '/5a17dd83-825c-42cf-84ce-e016f306933e';
>   documentation: '';
>   autoActivateUpdates: true;
>   execution: Single
>   {
>     query: |model::target::_Firm.all()->graphFetchChecked(#{model::target::_Firm{name,type,employees{fullName}}}#)->serialize(#{model::target::_Firm{name,type,employees{fullName}}}#);
>     mapping: mapping::ModelToModelMapping;
>     runtime:
>     #{
>       mappings:
>       [
>         mapping::ModelToModelMapping
>       ];
>       connections:
>       [
>         ModelStore:
>         [
>           connection_1:
>           #{
>             JsonModelConnection
>             {
>               class: model::Firm;
>               url: 'data:application/json,%7B%22employees%22%3A%5B%7B%22firstName%22%3A%22firstName%2019%22%2C%22lastName%22%3A%22lastName%209%22%7D%5D%2C%22legalName%22%3A%22legalName%2072%22%2C%22type%22%3A%22llc%22%7D';
>             }
>           }#
>         ]
>       ];
>     }#;
>   }
>   testSuites:
>   [
>     testSuite_1:
>     {
>       data:
>       [
>         connections:
>         [
>           connection_1:
>             ExternalFormat
>             #{
>               contentType: 'application/json';
>               data: '{\n  "employees": [\n    {\n      "firstName": "firstName 19",\n      "lastName": "lastName 9"\n    }\n  ],\n  "legalName": "legalName 72",\n  "type": "llc"\n}';
>             }#
>         ]
>       ]
>       tests:
>       [
>         test_1:
>         {
>           asserts:
>           [
>             assertion_1:
>               EqualToJson
>               #{
>                 expected : 
>                   ExternalFormat
>                   #{
>                     contentType: 'application/json';
>                     data: '{\n  "defects" : [ ],\n  "source" : {\n    "defects" : [ ],\n    "source" : {\n      "number" : 2,\n      "record" : "{\\"employees\\":[{\\"firstName\\":\\"firstName 19\\",\\"lastName\\":\\"lastName 9\\"}],\\"legalName\\":\\"legalName 72\\",\\"type\\":\\"llc\\"}"\n    },\n    "value" : {\n      "employees" : [ {\n        "firstName" : "firstName 19",\n        "lastName" : "lastName 9"\n      } ],\n      "legalName" : "legalName 72",\n      "type" : "llc"\n    }\n  },\n  "value" : {\n    "name" : "legalName 72",\n    "type" : "LLC",\n    "employees" : [ {\n      "fullName" : "firstName 19 lastName 9"\n    } ]\n  }\n}';
>                   }#;
>               }#
>           ]
>         }
>       ]
>     }
>   ]
> }
> ```

I am not sure I understand the consistency issue. Can you please provide more details?

**Comment by akphi** [comment]
Closing this since the major piece of work now falls on mapping test, so let's track this in https://github.com/finos/legend-studio/issues/1179
