### ISSUE TITLE
Feature request: Upgrade to react 18

### ISSUE THREAD

**Issue by akphi** [finos/legend-studio#1096]
### Similar requests

- [X] I have searched and found no existing similar requests

### What problems are you trying to solve?

We will need to upgrade to `react@18`

### Describe the solution you would like to see implemented

- [x] Do the upgrade, but we have to wait for libraries to catch up, **or we can just try to upgrade and hope these library work alright** - I scare the most of `mobx` though:
  - [ ] `react-reflex` https://github.com/leefsmp/Re-Flex/issues/158
  - [x] `mobx` https://github.com/mobxjs/mobx/pull/3005 https://github.com/mobxjs/mobx/issues/3370 https://github.com/mobxjs/mobx/issues/3363
  - [x] `react-window` https://github.com/bvaughn/react-window/issues/623
  - [ ] `react-resize-detector` https://github.com/maslianok/react-resize-detector/issues/206
  - [x] There are many libraries that are in questions: e.g. `react-reflex`, `react-hotkeys`
- [ ] Might need to upgrade `react-select` or do #615 
- [ ] Might want to upgrade `react-router` first #688 
- [x] Switch out to use `ReactDOM.createRoot` instead of `ReactDOM.render` - https://dev.to/mbarzeev/upgrading-a-create-react-app-game-to-react-18-4d5p
- [x] Take care of some `typings` changes - https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210 and https://solverfox.dev/writing/no-implicit-children/
- [ ] `MAYBE` try out `StrictMode`?

### Contribution

- [ ] I would like to work on this feature
