### ISSUE TITLE
Testable Flow Phase 2: Service Test Editor

### ISSUE THREAD

**Issue by MauricioUyaguari** [finos/legend-studio#1158]
### Similar requests

- [X] I have searched and found no existing similar requests

### How are you using Studio?

Legend Studio

### What problems are you trying to solve?
- Add Service Test Editor using Testable framework. 
- Simplify service execution editor
- Enhance create service by adding a mapping option

## TODO
- [x]  Requires https://github.com/finos/legend-studio/issues/1173 To be closed for the parameter editor
- [x] https://github.com/finos/legend-engine/pull/658 engine changes
- [x] Add mapping option when creating service 
- [ ]  Make `Edit Query` button a main button in service query 
- [ ]  Change `config` to `context` in execution panel. remove unnecessary testing panel in execution 
### Service Test Diagram
![image](https://user-images.githubusercontent.com/29690824/167916982-e5fa626d-13ca-4b1a-8c5f-1181b1e286f5.png)
