### ISSUE TITLE
Feature request: Query builder improvements (phase 2)

### ISSUE THREAD

**Issue by akphi** [finos/legend-studio#1342]
### Similar requests

- [X] I have searched and found no existing similar requests

### What problems are you trying to solve?

This `mega-thread` sums up the list of features/bug-fixes we need to do in order to make query builder production-ready.

### Describe the solution you would like to see implemented

- [x] @gayathrir11 Make the viewing of association non-recursive - https://github.com/finos/legend-studio/issues/1172 - differentiating between `association`:
- [x] @gayathrir11 Muting deprecated properties - #1310 
- [x] @gayathrir11 Highlight `already-used` properties in the explorer tree, (make it something configurable - similar to humanize property names, turned on by default) - https://github.com/finos/legend-studio/issues/1344
- [x] @gayathrir11 Warn users about stale result - https://github.com/finos/legend-studio/issues/1302 - https://github.com/finos/legend-studio/issues/1368
- [x] @gayathrir11 Block certain actions when the query is not valid: (1) duplicated projections? (2) duplicated parameters ... - https://github.com/finos/legend-studio/issues/1345
- [x] @akphi **FEEDBACK** Query Light-themed mode (do not change the layout too much and make the availability of this feature a config for this feature an Query standalone app) - https://github.com/finos/legend-studio/issues/1374
- [x] @akphi **FEEDBACK** Refactor setup page for query and setup area, support workstation mode/workflows for query, etc., rework query builder setup, optimize setup real-estate - #1300 
- [x] @akphi Rename `execute` to `run query` (`execute plan`, not `execute query`) - https://github.com/finos/legend-studio/pull/1343
- [x] @akphi Support editing query service directly in `Legend Studio` - https://github.com/finos/legend-studio/pull/1488
- [x] @akphi Support productionzing query, i.e. allow promoting query into service - https://github.com/finos/legend-studio/pull/1506
- [x] @akphi Improve clarity for `Legend Query` landing page to accommodate the need for different groups of users - https://github.com/finos/legend-studio/pull/1565
- [x] @xannem Should we allow query without projection/empty fetch structure, consider 2 possibilities: (1) default to graph-fetch, (2) show error when there are no projections - https://github.com/finos/legend-studio/pull/1386
- [x] @xannem **FEEDBACK** Improvements on property search, support air-quote when searching for properties - #1294 
- [x] @YannanGao-gs Ability to stop a query when running (fake it in the UI) - https://github.com/finos/legend-studio/issues/1357
- [x] @YannanGao-gs Allow loading query from inside of query builder (refer to DSB): we might need to add more metrics around a query, such as `latestDate`, etc. - https://github.com/finos/legend-studio/issues/1435
- [x] @YannanGao-gs **WORKFLOW-SPECIFIC** Should we allow DnD projection into `filter` panel - https://github.com/finos/legend-studio/pull/1350
- [x] @MauricioUyaguari **FEEDBACK** Should we allow fuzzy-search/auto-suggestion/auto-complete in filter https://github.com/finos/legend-studio/issues/1382
- [x] @MauricioUyaguari Validate parameters (duplication, i.e. milestoning stuffs) https://github.com/finos/legend-studio/issues/1269
- [x] @MauricioUyaguari _This is technically not a direct part of query builder but it's key to push our data space stategy_ - #1509 - this helps optimize dataspace loading performance

#### Needs more discussion/deprioritized

- [ ] @akphi @MauricioUyaguari Have some sort of indicator in `modal` dialogs if the changes the user made is already saved. i.e. use `popover` instead of `modal` for some
- [ ] @YannanGao-gs **FEEDBACK** How do we show help in virtual assistant for query? - Link to Keystone, support, level of satisfaction, dataspace support info
- [ ] @YannanGao-gs Allow selecting multiple properties for DnD/add to the projection panel - https://github.com/finos/legend-studio/issues/1354 - deprioritized, we will do this later
- [ ] @gayathrir11 Should we show a warning if the property is marked as sensitive: what is sensitive property? signified by stereotype? - deprioritized, we will do this later if needed

### Contribution

- [ ] I would like to work on this feature
