### ISSUE TITLE
Handle unsupported propagating functions with milestone properties

### ISSUE THREAD

**Issue by MauricioUyaguari** [finos/legend-studio#1471]
### Similar requests

- [X] I have searched and found no existing similar requests

### How are you using Studio?

Legend Studio

### What problems are you trying to solve?

There are functions that are not currently supported for date propagation. This leads to an uncompiled graph causing query builder to not be correctly opened.
Some examples are aggregation functions. 
 

### Describe the solution you would like to see implemented

- [ ] Figure out unsupported functions
- [ ] Function List
  - [ ] Aggregation
- [ ] TESTS 

### Contribution

- [ ] I would like to work on this feature
