### ISSUE TITLE
Feature request: Improvements to the query import modal

### ISSUE THREAD

**Issue by gayathrir11** [finos/legend-studio#2006]
### Implementation plan

| Query load flows   |  Rename | Preview | Delete | Last modified date | Filter by Class | Filter by dataspace | Filter by mine |
| -------------------- | ---------- | -------- | ------- | --------------------- | --------------- | --------------------  | --------------- |
|   Service execution editor                            |        ❎        |        ✔️       |      ❎      |           ✔️                      |             ❎            |      ❎                          |                  ✔️     |
| Load existing query (setup)  | ✔️ | ✔️  |✔️  | ✔️  |  ❎ |  ❎  | ✔️  |
| Productionize query (setup)  |  ❎| ✔️  | ❎ | ✔️  |  ❎ |  ❎  | ✔️  |
| Load existing query (query editor)  | ✔️ | ✔️  |✔️  | ✔️  |  ❎ |  ❎  | ✔️  |
| Load existing query (from dataspace)  | ✔️ | ✔️  |✔️  | ✔️  | ✔️  | ✔️   | ✔️  |

***Engine work***
- [x] Modify search endpoint to return last modified date for a query finos/legend-engine#1535
- [x] Support searching queries by query id finos/legend-engine#1609
     
***General design of import modal***

- Filter Options

    - Mine only
    
- Advanced options
    
     - Preview
     
***Studio Tasks***

- [x] Send `classPath` as tagged value when we save/update queries so that we can filter via class #2018 
- [x] Add a generic load query importer
- [x] Customize load query importer for all workflows via extensions
- [x] Limit to search to list of top 10 queries
- [x] Make the minimum search text to be 3 letters
- [x] Leverage `localStorage` to store list of 10 query ids most used by the user (update the list stored whenever user tries to access a new query. Use concept of caching here)
- [ ] Add metrics around the operations getting added (THINK)

**Comment by akphi** [comment]
| Query load flows                     | Rename | Preview | Delete | Last modified date | Filter by Class | Filter by dataspace | Filter by mine |  | SearchModified                      | View | Free |                                    |
| ------------------------------------ | ------ | ------- | ------ | ------------------ | --------------- | ------------------- | -------------- |  | ----------------------------------- | ---- | ---- | ---------------------------------- |
| Service execution editor             | ❎      | ✔️      | ❎      | ✔️                 | ❎               | ❎                   | ✔️             |  | x                                   | x    | x    | <- should be scoped to the project |
| Load existing query (setup)          | ✔️     | ✔️      | ✔️     | ✔️                 | ❎               | ❎                   | ✔️             |  | x                                   | x    |      |                                    |
| Productionize query (setup)          | ❎      | ✔️      | ❎      | ✔️                 | ❎               | ❎                   | ✔️             |  | x                                   | x    |      |                                    |
| Load existing query (query editor)   | ✔️     | ✔️      | ✔️     | ✔️                 | ❎               | ❎                   | ✔️             |  | x                                   | x    | x    |                                    |
| Load existing query (from dataspace) | ✔️     | ✔️      | ✔️     | ✔️                 | ✔️              | ✔️                  | ✔️             |  | x                                   | x    | x    |                                    |
|                                      |        |         |        |                    |                 |                     |                |  |                                     |      |      | POST /search                       |
|                                      |        |         |        |                    |                 |                     |                |  |                                     |      |      | POST /relevants                    |
|                                      |        |         |        |                    |                 |                     |                |  | Sort order                          |      |      |                                    |
|                                      |        |         |        |                    |                 |                     |                |  | owned by user last modified         |      |      |
|                                      |        |         |        |                    |                 |                     |                |  | recently viewed by user             |      |      |
|                                      |        |         |        |                    |                 |                     |                |  | free (ordered by recently modified) |      |

**Comment by akphi** [comment]
| Query load flows                     | Rename | Preview | Delete | Last modified date | Filter by Class | Filter by dataspace | Filter by mine |  | SearchModified                      | View | Free |                                    |
| ------------------------------------ | ------ | ------- | ------ | ------------------ | --------------- | ------------------- | -------------- |  | ----------------------------------- | ---- | ---- | ---------------------------------- |
| Service execution editor             | ❎      | ✔️      | ❎      | ✔️                 | ❎               | ❎                   | ✔️             |  | x                                   | x    | x    | <- should be scoped to the project |
| Load existing query (setup)          | ✔️     | ✔️      | ✔️     | ✔️                 | ❎               | ❎                   | ✔️             |  | x                                   | x    |      |                                    |
| Productionize query (setup)          | ❎      | ✔️      | ❎      | ✔️                 | ❎               | ❎                   | ✔️             |  | x                                   | x    |      |                                    |
| Load existing query (query editor)   | ✔️     | ✔️      | ✔️     | ✔️                 | ❎               | ❎                   | ✔️             |  | x                                   | x    | x    |                                    |
| Load existing query (from dataspace) | ✔️     | ✔️      | ✔️     | ✔️                 | ✔️              | ✔️                  | ✔️             |  | x                                   | x    | x    |                                    |
|                                      |        |         |        |                    |                 |                     |                |  |                                     |      |      | POST /search                       |
|                                      |        |         |        |                    |                 |                     |                |  |                                     |      |      | POST /relevants                    |
|                                      |        |         |        |                    |                 |                     |                |  | Sort order                          |      |      |                                    |
|                                      |        |         |        |                    |                 |                     |                |  | owned by user last modified         |      |      |
|                                      |        |         |        |                    |                 |                     |                |  | recently viewed by user             |      |      |
|                                      |        |         |        |                    |                 |                     |                |  | free (ordered by recently modified) |      |
