### ISSUE TITLE
Feature request: Editor support for relational (MVP)

### ISSUE THREAD

**Issue by akphi** [finos/legend-studio#202]
We will start building forms to edit relational-related entities (i.e. stores, mappings, connections, diagrams, etc.). This is not meant to be exhaustive but just the MVP, which lists out items to be done in order of priority. We will keep this around until we're happy with the MVP and move the remaining outstanding items to another thread.

### Implementation Plan

- [x] Relational mapping source selector (https://github.com/finos/legend-studio/pull/207)
  - [x] `API` expose an engine API to transform (grammar \<-\> JSON) relational operation element (https://github.com/finos/legend-engine/pull/232)
  - [x] Leave relational operation element raw in relational property mapping
  - [x] Operation element editor
  - [x] Source tree need to support joins
  - [x] Support DnD for joins from source-tree
- [x] Relational mapping execution panel: note that we will use `H2` for this
  - [x] Use query builder
  - [ ] Auto-generate test data (currently blocked by `engine`)
- [x] Relational mapping test panel
  - [x] Create an API that takes in mapping, model, source/target class -> generate test data: this API will accommodate for M2M use case as well (and potentially flat-data), if there is no connection specified -> use H2, do some dummy data generation (if it gets too complicated, throw?), if there is a connection specified -> use the API that we haven't released yet
  - [x] Create a protocol to hold relational mapping test and make it work with test runner (https://github.com/finos/legend-engine/pull/238)
- [ ] Basic support for database editor
  - [ ] Be able to generate store from connection
  - [ ] Basic join editor (need more investigation, we can take a look at `Microsofts Access`)
- [ ] More advanced lambda builder for relational property mapping: supports `function compose`, `group operators`, `filter`, `groupBy`, etc.
- [ ] Support identifying/interpreting `Primary Key (PK)` in relational mapping
- [ ] Support embedded relational property mapping

**Comment by akphi** [comment]
Close this to open smaller issues
