### ISSUE TITLE
RFC: Rework query builder graph fetch support

### ISSUE THREAD

**Issue by akphi** [finos/legend-studio#204]
## 💬 Request for Comments

The graph fetch support MVP that we have right now doesn't really have the best UX, for one thing, it is inconsistent with the projection counterpart, which is `DnD`-based

### Implementation Plan
- [ ] Use DnD for graph fetch construction: note that we don't need to support `derived property parameters`, `alias`, or `sub-typing` right now
- [ ] Remove the flag that disables graph fetch support in query builder
- [ ] Change other places that are currently using graph fetch tree (i.e. mapping execution/test panel) to switch out to use the query builder like in service editor. The default mode before entering query builder will be `text mode` like in service editor
