### ISSUE TITLE
RFC: (mega-thread) Execution plan viewer

### ISSUE THREAD

**Issue by MauricioUyaguari** [finos/legend-studio#249]
### Motivation

The execution plan holds all the information required for the engine server (legend-engine) to execute a query. With this viewer, we plan to shed some light on the context of the execution plan and showcase to the user the steps taken to execute their queries to provide the data in the shape they want it.

Since the execution plan holds various types of nodes for different types of queries and data sources, it is not feasible to inaugurate a user interface covering all use cases. For this reason, this feature will be implemented in steps. We will cover basic relational, model-to-model cases in the beginning and lead up to more advanced use cases. For the nodes not supported we will default to a basic JSON string viewer.

### Implementation

As mentioned above we will tackle the viewer through phases. When creating the viewer for each phase, the steps will be similar to adding support for a new packageable element except there is no need for transformation as the execution plan viewer is a **readonly** UI for now. Therefore to add support please follow the below steps. 

- [x] Add `V1_ExecutionPlan` models (#248)
- [x] Add V1 serializer/de-serializer support to convert from/to raw JSON and `V1_ExecutionPlan` Models (#248)
- [x] Add metamodel `ExecutionPlan` models (#248)
- [x] Add Execution Plan builder converting `V1_ExecutionPlan` protocol to `ExecutionPlan` metamodel (and potentially vice versa so we can do more testing) (#248)
- [x] Use the metamodel `ExecutionPlan` to create a viewer. Using the metamodel execution plan will provide you with the compiled metamodel graph to be able to quickly find referenced elements in the graph such as classes, mappings, and runtimes. 
- [x] MVP execution plan viewer interface (See https://github.com/finos/legend-studio/issues/289)
- [ ] In plan viewer, classify the nodes in different buckets, and render them differently:
  - [ ] Flow control (sequence/conditional/loop/...)
  - [ ] Templating node (free-marker)

#### Execution Plan
See Attached Execution Plan Json
[ExecutionPlan_Phase_1.txt](https://github.com/finos/legend-studio/files/6635388/message.2.txt)

#### Pure Grammar
 ```
###Relational
Database model::Test
(
  Table FirmTable
  (
    id INTEGER PRIMARY KEY,
    Legal_name VARCHAR(200)
  )
  Table PersonTable
  (
    id INTEGER PRIMARY KEY,
    firm_id INTEGER,
    firstName VARCHAR(200),
    lastName VARCHAR(200)
  )

  Join FirmPerson(PersonTable.firm_id = FirmTable.id)
)


###Pure
Profile model::MyExtension
{
  stereotypes: [important];
  tags: [doc];
}

Enum model::IncType
{
  Corp,
  LLC
}

Class <<model::MyExtension.important>> {model::MyExtension.doc = 'This is a model of a firm'} model::Firm extends model::LegalEntity
[
  validName: $this.legalName->startsWith('_')
]
{
  employees: model::Person[1..*];
  incType: model::IncType[1];
  employeeSize() {$this.employees->count()}: Number[1];
}

Class model::LegalEntity
{
  legalName: String[1];
}

Class model::Person
{
  firstName: String[1];
  lastName: String[1];
}


###Mapping
Mapping model::NewMapping
(
  *model::Firm: Relational
  {
    ~primaryKey
    (
      [model::Test]FirmTable.id
    )
    ~mainTable [model::Test]FirmTable
    legalName: concat([model::Test]FirmTable.Legal_name, '_LTD'),
    employees[model_Person]: [model::Test]@FirmPerson
  }
  *model::Person: Relational
  {
    ~primaryKey
    (
      [model::Test]PersonTable.id
    )
    ~mainTable [model::Test]PersonTable
    firstName: [model::Test]PersonTable.firstName,
    lastName: [model::Test]PersonTable.lastName
  }

  MappingTests
  [
    test_1
    (
      query: |model::Firm.all()->project([x|$x.legalName, x|$x.employeeSize, x|$x.employees.firstName, x|$x.employees.lastName], ['Legal Name', 'Employee Size', 'Employees/First Name', 'Employees/Last Name']);
      data:
      [
        <Relational, SQL, model::Test,
          'Drop table if exists FirmTable;\n'+
          'Drop table if exists PersonTable;\n'+
          'Create Table FirmTable(id INT, Legal_Name VARCHAR(200));\n'+
          'Create Table PersonTable(id INT, firm_id INT, lastName VARCHAR(200), firstName VARCHAR(200));\n'+
          'Insert into FirmTable (id, Legal_Name) values (1, \'FirmX\');\n'+
          'Insert into PersonTable (id, firm_id, lastName, firstName) values (1, 1, \'John\', \'Doe\');\n'
        >
      ];
      assert: '{"columns":["Legal Name","Employee Size","Employees/First Name","Employees/Last Name"],"rows":[{"values":["FirmX_LTD",1,"Doe","John"]}]}';
    )
  ]
)

**Comment by akphi** [comment]
🚒
