### ISSUE TITLE
RFC: Query builder: Support derivation in projection

### ISSUE THREAD

**Issue by akphi** [finos/legend-studio#254]
## 💬 Request for Comments
Right now the only type of lambda that is supported in the query builder projection column is a property expression. We should allow any expression to be typed.

## Context and Motivation
We want to support use cases like the following:

```
test::Person.all()
   ->project
    (
      [
        x|$x.lastName + $x.firstName
      ], 
      [
        'Full Name'
      ]
    )
```

## Implementation Plan
In terms of behaviour:

- In the projection panel, user click + (Add derivation)
- We show a lambda editor
- User can drag and drop from the explorer on the left or they can type something

In terms of validation:
- Use lambda editor so we have parsing error taken care of
- DISCUSS should we do type-checking using /compile/lambdaReturnType API? If we have the type, we can use that to reason the aggregation. But we don't do this at the beginning when we load the function, how should we handle that case then, should we take that as unknown type and leave the aggregation (if present) untouched or something?
In terms of state management:

Processing:
- Detect non-property lambda in columns of project()
- State building:
- Add another shape on top of property for the projection columns
- Lambda building (from state):
- Introduce ._raw?: object to metamodel ValueSpecification
- Allow F9 in query builder, we will fall back to text mode for error handling
If we can do this, we can also support derivation in filter and aggregation. We might need to address this right away anyway for aggregation, if we identify that the first lambda of agg() is derivation, we cannot do much with the aggregate lambda, we might just at this point treat it like anything, this means we might need to support a new type of aggregation operator - i.e. custom.

#### Steps

- [x] Support compilation in form mode
- [x] Support `roundtrip` for processing unsupported column expressions in `project() expression`
- [x] Support reveal compilation errors in form mode for derivation
- [x] Support adding new property in form mode
  - [x] Support `+` - default to `x|''`
  - [x] Support DnD
- [x] Support `roundtrip` for processing unsupported column expressions in `groupBy() expression`

#### Optional
- [x] Support using hotkey F9 to compile in query builder
- [x] Write a changeset for derivation feature
- [x] ~~Support custom aggregation - default to `x|x->count()`~~ -> after discussion, this does not seem to make a lot of sense since we should only allow a fairly restricted sets of functions for aggregation
- [x] ~~Support custom filter - default to `x|true`~~ ->  This could make sense, but we would move it back to the main thread
https://github.com/finos/legend-studio/issues/256

**Comment by akphi** [comment]
**NOTE**: Updated this to `Feature Request` instead of `RFC`
