### ISSUE TITLE
Feature request: Database Builder 

### ISSUE THREAD

**Issue by MauricioUyaguari** [finos/legend-studio#268]
## 🚀 Feature Request

Provide a friendly and seamless user interface for generating a database definition given connection information. 

### Motivation
To provide a better user experience when creating a store definition. Users should be able to build their store definition by defining connection details and with a UI to select the subset of schemas/tables/views they want in their store definition. 

## # Implementation
Like many features, we plan on working through this feature in phases.

#### Phase 1 - POC
- [x ] Provide POC of database builder to showcase goal of generating database
- [ x] `FEEDBACK` provide more **exploratory** view. Users should see schemas and lazy load relevant schemas/tables of interest. 

### Phase 2
- [ ] Refactor api to builder database
- [ ] OSS api
- [ ] Exporatory View
       - [ ] fetch and display all schemas of given connection
       - [ ] lazy load tables
       - [ ] check box next to each schema, table
       - [ ] generated `read only` grammar on right side
       - [ ] feedback

### Thoughts for phase 3? 
- provide column filtering support
- drag and drop from left to right
- delta calculation
