### ISSUE TITLE
Feature request: Simplify metamodels

### ISSUE THREAD

**Issue by akphi** [finos/legend-studio#275]
To prepare for #263, we need to simplify metamodels so that these can be auto-generated from models in Pure.

### Implementation Plan

- [x] Move the `lambdaId` to stores (https://github.com/finos/legend-studio/pull/227)
- [ ] For fields that we added to support better graph navigation (i.e. `owner`, `parentClass`, etc.`) that are not in the actual metamodel, we should prefix them with `_`, such as `_owner`
- [ ] Remove `super.something`. This might involve using `mobx` `override` flag for `action`s and `computed`s
- [ ] Remove rendering logic like `Stubable` and `label`
- [ ] Move `PackageableElementSelectOption` back into `stores`, don't leave those in `graph` and `metamodels`
- [ ] Move helpers logic into corresponding classes `MappingHelpers`, `PackageableElementHelpers` like in `finos/legend-pure`
- [ ] Remove all constructor parameters

**Comment by akphi** [comment]
Closing for now, merging thread back into #263
