### ISSUE TITLE
RFC: Rework New-Element creation flow

### ISSUE THREAD

**Issue by akphi** [finos/legend-studio#277]
## 💬 Request for Comments

We should rework our current fairly rudimentary interface for creating new elements.

### Implementation Plan

- [ ] Show the full path of the element in the name box (almost like IntelliJ when you create a new element)
- [ ] Beautify the element creation modal - refer to new project modal in `IntelliJ`
- [ ] Clicking the plus `+` button in project explorer will open up the modal, where the right-clicking will not
- [ ] `CONSIDER` Adding multi/nested context-menu for new element, change + to open modal to create new element instead
- [ ] `CONSIDER` We can explore the design from `VS Code` dropdown in `Settings` that shows more information about the currently focused item in the dropdown, or Gmail when hovering on each Inbox folder
<img width="902" alt="gmail" src="https://user-images.githubusercontent.com/13574879/122999498-5925ff80-d37c-11eb-875d-d3750fe1a36b.png">
<img width="540" alt="dropdown with info and default indicator and more info on focus" src="https://user-images.githubusercontent.com/13574879/122999836-c33ea480-d37c-11eb-8502-659bb67f360e.png">
<img width="472" alt="dropdown with info and default indicator and more info on focus 2" src="https://user-images.githubusercontent.com/13574879/122999852-c6d22b80-d37c-11eb-8e29-04a55136850d.png">

**Comment by akphi** [comment]
Also consider the following refactor at code-level
  - [ ] Restrict the usage of type classifier and consider using the element instead the only mechanism that really needs the type classifier is element creation, which we could refactor to have a plugin that produces a single configuration for the creation ceremony: e.g. `type ElementCreatorConfiguration = { key: string; label: string; icon: React.ReactNode; ... }`
  - [ ] Reorganize elements in the dropdown to create new elements: core elemtns goes first, but should be sorted alphabetically, extensions go later and sorted alphabetically as well
  - [ ] Remove `ModelClassifierUtils`
