### ISSUE TITLE
RFC: Better notification management

### ISSUE THREAD

**Issue by akphi** [finos/legend-studio#291]
## 💬 Request for Comments

Our notification system is rather basic at the moment:
- We only show **one** notification at a time.
- We don't store notification history.
- Our display of notification is messy and unfriendly with multi-line notifications.

### Implementation Plan
- [ ] `STUDY` Refer to `vscode` notification system: history management, interactions, etc.
- [ ] Make notification a stack that is clearable
- [ ] Support showing multiple notifications at a time - See [notistack](https://github.com/iamhosseindhv/notistack). `material-ui` Snackbar also [works with](https://material-ui.com/components/snackbars/#notistack) `notistack`
- [ ] Truncate the notification and allow expanding them to see more
