### ISSUE TITLE
RFC: Viewer mode improvements

### ISSUE THREAD

**Issue by akphi** [finos/legend-studio#297]
## 💬 Request for Comments

Viewer mode allows user to enter a read-only workspace that corresponds to the current HEAD of the project, we should come up with a set of features that we should allow in this mode. Modifications to models should be blocked. This can set us up on the right path should we update review mode to also allow users to interact with the read-only workspace.

### Implementation Plan
- [ ] Allow seeing project configuration
- [ ] Allow hackermode/text-mode
- [ ] Allow opening model loader
- [ ] Allow using query builder
