### ISSUE TITLE
Feature request: Diagram editor improvements

### ISSUE THREAD

**Issue by akphi** [finos/legend-studio#300]
### Rework
- [x] Handle the case where elements shown in diagram are removed or changed (i.e. properties/classes/tagged-values/associations/etc.) - Related to #335 - We need to create an `auto-heal` mechanism that scans all diagrams in the graph and fix them, also, rerender them upon completion (See https://github.com/finos/legend-studio/pull/351):
  - [x] When we delete an element (association and class)
  - [x] When we delete a property
  - [x] When we delete a supertype
  - [x] When we change a property type
- [x] Make diagram resize box indicator more apparent, we should change the cursor to indicate resizability (we can even expand resize ability to allow resizing from the sides and any corners) - See https://github.com/finos/legend-studio/pull/349
- [x] Zoom should take into the current position of the current instead of zooming from the centre of the diagram - https://github.com/finos/legend-studio/pull/350

### New features
- [ ] Support association (we need to also consider how the `auto-heal` work with association and https://github.com/finos/legend-studio/issues/282)
- [ ] Support deleting `property`, `class`,` inheritance`, etc. (not just class view) -> potentially by setting up some hotkeys like `Shift+Delete` or do some right-clicking action
- [ ] https://github.com/finos/legend-studio/issues/128
- [ ] https://github.com/finos/legend-studio/issues/127
- [x] When we do a single click to select a class view, the class view should be shown on the side bar to allow edit information like `hideProperties`, `hideStereotypes`, etc. (and potentially when we improve the model to accept line width, and color, etc.) - See #350 
- [x] Allow aligning elements in the diagram - https://github.com/finos/legend-studio/pull/350
- [x] Show tool panel and hotkey guide for diagram viewer (right now we don't really display the hotkeys cheatsheet anywhere) - See https://github.com/finos/legend-studio/pull/340
- [x] Support right-clicking on a class view and hit execute? (https://github.com/finos/legend-studio/pull/584)
- [x] Show class supertypes and subtypes (https://github.com/finos/legend-studio/pull/361)

### To be considered
- [ ] Introduce theme/color-scheme to diagram and make it more customizable
- [ ] Allow searching for class/property in the diagram and have it zoomed in
- [ ] Allow modifying color of diagram - this requires changes in the model of diagram
- [ ] Allow specifying a function to dynamically change color of the diagram class view
- [ ] `DISCUSS?` Remove the usage of `offset` in relationship view
- [x] ~~Allow inline editing for class and property directly on the diagram~~ - Implemented in https://github.com/finos/legend-studio/pull/349 but later remove as we deem it not too useful (we are encroaching the realm of auto-layout but that needs a lot of discussion)

**Comment by akphi** [comment]
I'll just close this and will bring back it in forms of smaller separate issues when there's interest again.
