### ISSUE TITLE
RFC: Rework Modes

### ISSUE THREAD

**Issue by akphi** [finos/legend-studio#317]
## 💬 Request for Comments

Within Studio, we currently support 3 modes: `editor`, `viewer`, and `review`, each is somewhat being treated differently: e.g. `viewer` mode does not allow editing elements, `review` mode does not allow viewing and working with the element, etc. When `query builder` becomes standalone, we might need to yet support another mode. What we realize is,  these modes are not too far off from one another. In fact, we are trying to bring them closer in functionalities - see https://github.com/finos/legend-studio/issues/297.

In fact, we should consider all the flows and just make them different in a very small set of features. Instead of thinking that we should create a brand new mode without any functionality and then adding them one by one (like what we're trying to do in https://github.com/finos/legend-studio/issues/297), we probably should start using `EditorStore` and having ways to disable certain features if that's cleaner. i.e. starts from the full one - `editor mode` - and see what we can turn off

### Implementation Plan

- [ ] Viewer mode:
  - [ ] Disable saving/Review/Workspace Updater
  - [ ] Keep the LocalChange panel around, but then have a feature so that people can make changes to model and if they like, they can create a new workspace with these changes (almost like `git checkout -b <branch_name>` behaviour)
- [ ] Review mode:
  - [ ] Disable saving/review/Workspace updater
- [ ] Query builder viewer mode - this is the base for the standalone query builder
  - [ ] Disable editing everything, everything would be readonly (similar to the current viewer mode)
