### ISSUE TITLE
Feature request: Rework query builder layout

### ISSUE THREAD

**Issue by akphi** [finos/legend-studio#318]
Rework query builder layout to prepare for standalone query builder.

### Implementation Plan

- [ ] Move runtime down to the result panel somehow
- [ ] Create a model loader (in dialog form) just like the main Studio app
- [ ] Relayout:
  - [ ] Sidebar: Explorer
  - [ ] Auxiliary Panel
  - [ ] Status bar
  - [ ] Edit Panel
  - [ ] Text mode will no longer be a modal
- [ ] Rework text-mode to not use `LambdaEditor` but do something similar to `GrammarEditorTextMode`

**Comment by akphi** [comment]
Most of the points brought up here are no longer relevant so closing
