### ISSUE TITLE
Feature request: Support `workflows` in query builders

### ISSUE THREAD

**Issue by akphi** [finos/legend-studio#319]
Query builder might be used in different workflows right now:

- Data browsing mode: the current query builder where the query is expected to be of shape `SomeClass.all()...`
- Advanced/Unsupported mode: the query can be of any form

As such, we come up with this idea to add a new feature to the query builder - `workflows`. Think of Adobe Photoshop [workspace](https://helpx.adobe.com/photoshop/using/workspace-basics.html) feature: you can pick the flow that works best for you - `Illustration`, `Photography`, etc.

### Implementation Plan

- [ ] Add new feature: `Workflow`
  - [ ] `Workflow` bundles plugins together and there should be a generic check for when `workflow` is applicable and instruction on what happens when switching between `workflows`
  - [ ] Add the workflows as mentioned in the previous section
  - [ ] Workflow can also take a config to show/hide elements: hide result panel, etc.

**Comment by akphi** [comment]
Closing this as many parts of it has been done or out-of-date. The idea is not bad, but we should revisit this design in the future

**Comment by akphi** [comment]
I have updated the implementation plan in more details in https://github.com/finos/legend-studio/pull/1453
