### ISSUE TITLE
Feature request: Support renaming element

### ISSUE THREAD

**Issue by akphi** [finos/legend-studio#322]
## 🚀 Feature Request

We are putting up a placeholder for element renaming now in Studio: when user right-click on an element, one would see `Rename (WIP)`

### Implementation plan

- [x] Create a modal for renaming: we need a validator here because this operation is very sensitive
- [x] Update element `name`
- [x] Update element `package`
- [x] Update index in the graph
- [x] Update project tree
- [x] Make sure to call compilation in the end (like `deleteElement`)
- [x] Rerender currently opened diagram (just in case it's affected by the rename)
- [x] Handle the recursive renaming when we rename a package
