### ISSUE TITLE
RFC: Query builder standalone MVP

### ISSUE THREAD

**Issue by akphi** [finos/legend-studio#325]
## 💬 Request for Comments

We want to build a standalone query builder for folks who want to explore data without having to do modelling. These are meant for `playground` only, these queries being built can be saved, but not meant for production, production queries will need to have proper SDLC strategy and that would go through Studio in forms of `services`.

### Implementation Plan

- [ ] Query builder app store:
  - [ ] Can we just reuse `EditorStore` or we should abstract the part of it that can be shared with `query builder`?
- [x] `NOTE` Use `SDLC` server until we open source `legend-depot`
  - [x] Show all exsiting versions
  - [x] Show the SNAPSHOT version (`master` branch of project)
- [x] Setup page:
  - [x] Pick the `project`
  - [x] Pick the `version`
  - [x] Pick the `query` from the list of:
    - [x] Type 1: Service (we use the service name + execution key: we also show the label with the Mapping + Runtime)
    - [x] Type 2: Query name (with label: Mapping + Runtime info)
    - [x] Type 3: `Create new...`
  - [x] After choosing the query from the list, we show a selector for the mapping and the runtime:
    - [x] For the case of `Type 1` and `Type 2`, the mapping and runtime are fixed, the only action here is `Next`
    - [x] For the case of `Type 3`, the mapping and runtime is selectible (runtime is scoped by the mapping)
- [x] URL handling:
  - [x] Setup page: `/query/setup`
  - [x] Type 1: `/query/{projectId}/{version}/service/{serviceName}?key=...`
  - [x] Type 2: `/query/{projectId}/{version}/{queryName}`
  - [x] Type 3: `/query/{projectId}/{version}/new?mapping=...&runtime=...`
- [x] Work in `finos/legend-engine` - Done in https://github.com/finos/legend-engine/pull/333 and https://github.com/finos/legend-engine/pull/341
