### ISSUE TITLE
Feature request: Show workspace status in setup page

### ISSUE THREAD

**Issue by akphi** [finos/legend-studio#326]
## 🚀 Feature Request

We could make use of the `/projects/{projectId}/conflictResolution` and `/projects/{projectId}/backup` to derive the status of workspaces in Studio and better allow people to take actions such as backup or delete right from the home page

### Implementation Plan

- [ ] Fetch backup workspaces
- [ ] Fetch conflict resolution workspaces
- [ ] Show indicator if workspace is in conflict resolution state (validate it ONLY has a normal workspace with it - otherwise, it is in BAD state)
- [ ] Show indicator if workspace is in backup state (there are only 2 possible states: when the original workspace still exists -> backup would be a `forced backup`, when there is none, we will do a normal backup)
- [ ] Replace the action button on the screen from `Next` to `Resolve Conflict`, `Backup`. For workspaces in bad state. Do not show any action
