### ISSUE TITLE
RFC: Time traveling - `undo/redo` support

### ISSUE THREAD

**Issue by akphi** [finos/legend-studio#327]
### Context and Motivation

Undo can be implemented in 2 ways:
- Taking snapshots of the state
- Recording the diff and knowing how to replay/rewind the diff action

The latter is not possible in Studio just yet, we need more planning for that because not all of our actions are easily rewindable since our editing actions are very diverse in nature: we're a form editor so there are a lot of interactions users can make, and it's hard to list out all of them as well as having a generic way to `revert` these changes; whereas for a text editor, the coordinate for the changes are well-defined and changes can be easily pinpointed, reverted, and compactly stored. This means that we most likely take the former approach.

However, Studio's form editor supports `live-editing`, which makes it hard to do snapshotting. `live-editing` refers o things like `input`, `text-area` where one can just type directly and the state and the metamodel values are updated continuously, which puts us at the risk of creating snapshots too often.

The prevalent way form editors implement `undo/redo` is by avoiding `live-edit`. Imagine a text value being displayed, but to edit it, one needs to click `Edit` and then start typing and then once done, hits `Save`, we can then take snapshot at the `save` action. However, we can use `debounce`, `throttle` to limit the number of snapshots taken in `live-editing`.

We want to consider supporting this for `Studio` and `query`. They might differ in how we take snapshots. For query, the state is small, we can take snapshots of the full query. For `Studio`, we can't really afford this since the graph is huge, instead, we will only take snapshots of the element that was modified (We can store this like a diff - see model below)

```ts
// subjected to further discussion
class ElementModification {
  oldPath: string;
  newPath: string;
  oldContent: object;
  newContent: object;
  ...
}
```

### Implementation Plan

- `Query`:
  - [ ] Create a method to take snapshot, and replay snapshot. If we need to support `redo`, we can keep track of `redo stack`, if new snapshot is push and it does not match the redo top element, we will flush the `redo` stack 
  - [ ] Add `updateSnapshot` to the end of every modifications (throttle when we do `live-editing`)
  - [ ] Support `Ctrl+Z`, we don't need to worry about this overshadowing `lambda editor` which uses `monaco-editor`, `monaco-editor`'s hotkeys take precedence and they handle `undoing` naturally.
- `Studio`: Same as query, except we need to rebuild the graph on every `undo`, `redo` potentially
