### ISSUE TITLE
Feature request: Support mechanism to apply changes patch

### ISSUE THREAD

**Issue by akphi** [finos/legend-studio#470]
### Context and Motivation
We allow users to download a patch for their local changes, but there's no way to apply it. This might play out as a _mini_ conflict-resolver (i.e. think of when we do `git stash pop/apply` and have to resolve the conflicts then), so the UI work might be quite involving. Nevertheless, this is a natural step to improve the current SDLC as it helps users recover their workspaces, and will help with working within a group workspace in particular (see https://github.com/finos/legend-studio/issues/461)

### Implementation Plan

- [ ] Compute the diff between the base revision and the current revision
- [ ] Compute conflicts between the 2 sets of changes
- [ ] Create an interface (similar to conflict resolution) to resolve the conflict, in the end, we end up with changes in the workspace

**Comment by akphi** [comment]
Moved this out of `3.0.0` as the core part is already handled in #748 . The enhancement to handle conflict resolution can be done later
