### ISSUE TITLE
RFC: Refactor to use SDLC `Workflow` API

### ISSUE THREAD

**Issue by akphi** [finos/legend-studio#474]
## 💬 Request for Comments

`Build` API has been deprecated, we should adapt to use `Workflow` instead 

### Implementation plan
- [x] Add `Workflow` and `WorkflowJob` models
- [x] Add APIs for `Workflow` in `SDLC client`
- [x] Refactor `Builds` side bar to use `Workflow`
- [x] Rename panel to `Workflow Jobs` or `Workflow` instead
