### ISSUE TITLE
RFC: Support form editor for mapping filter (phase 1)

### ISSUE THREAD

**Issue by kshradhan** [finos/legend-studio#497]
### Context and Motivation
Right now the only way to know if a particular mapping has a filter is to go to text mode, which is quite uncomfortable, we should think of a way to show the filter right in the mapping editor, we can show the filter in read-only text editor for now.

Potentially, we can show the filter as an item in the mapping explorer. 

Phase 2 of this will be tracked in https://github.com/finos/legend-studio/issues/542

### Implementation Plan

- [x] Visibility: Show filter icon on the right side of the entities with filters inside the Mapping Panel
- [X] Editability: Add LambdaEditor below Properties Panel to edit the filters directly (refer to how we do `Constraints`)
- [X] UX: Allow user to right-click the entity and add filter

## Example Code
```
Class model::Person
{
  name: String[1];
  age: Number[1];
}

Class model::PersonSource
{
  firstName: String[1];
  lastName: String[1];
  age: Number[1];
}


###Mapping
Mapping model::Mapping
(
  *model::Person: Pure
  {
    ~src model::PersonSource
    ~filter $src.firstName->startsWith('A')
    name: $src.firstName + $src.lastName,
    age: $src.age
  }

  MappingTests
  [
    test_1
    (
      query: |model::Person.all()->graphFetch(#{model::Person{age,name}}#)->serialize(#{model::Person{age,name}}#);
      data:
      [
        <Object, JSON, model::PersonSource, '[{"firstName":"AfirstName 9","lastName":"lastName 67","age":89},{"firstName":"BfirstName 9","lastName":"lastName 67","age":12}]'>
      ];
      assert: '{"age":89.0,"name":"AfirstName 9lastName 67"}';
    )
  ]
)
```

**Comment by akphi** [comment]
**NOTE**: Updated this to `New Feature` instead of `RFC`
