### ISSUE TITLE
RFC: Text mode support for DSL Serializer

### ISSUE THREAD

**Issue by gayathrir11** [finos/legend-studio#507]
### Implementation Plan

- [x] Add text mode support for Schema Set
- [x] Add text mode support for Binding
- [x] Add text mode support for External Format Connection
- [x] Create extension mechanism to move serializer connection related logic out from core
- [x] Re-organize code for external format connection

**Comment by akphi** [comment]
Hey @gayathrir11, thanks for filing this issue! Could we rephrase the 4th step to something like: create extension mechanism to move serializer connection-related logic out from core

**Comment by akphi** [comment]
**NOTE**: Updated this to `New Feature` instead of `RFC`
