### ISSUE TITLE
RFC: Support form editor for mapping filter (phase 2)

### ISSUE THREAD

**Issue by akphi** [finos/legend-studio#542]
## 💬 Request for Comments

This is the continuation of https://github.com/finos/legend-studio/issues/497

### Implementation Plan

Some of the work has been handled by #437 

- [ ] Move `InstanceSetImplementationSourceExplorer` out to a separate file
- [ ] Refactor so for each subtype of `InstanceSetImplementationState`, we have a corresponding `InstanceSetImplementationEditor`, right now we start having too many `instanceof` logic in this component which is only getting worse
- [ ] Add support for `relational` filter in form mode as well

**Comment by akphi** [comment]
Could you acquire a grammar example for relational filter so we can add it to this RFC?

**Comment by kshradhan** [comment]
```SQL
###Relational
Database model::Test
(
  Table FirmTable
  (
    id INTEGER PRIMARY KEY,
    Legal_name VARCHAR(200)
  )
  Table PersonTable
  (
    id INTEGER PRIMARY KEY,
    firm_id INTEGER,
    age INTEGER,
    firstName VARCHAR(200),
    lastName VARCHAR(200)
  )

  Join FirmPerson(equal(PersonTable.firm_id,FirmTable.id))

  Filter AboveThirty(PersonTable.age > 30)
)


###Pure
Class model::Firm
{
  employees: model::Person[1..*];
  employeeSize() {$this.employees->count()}: Number[1];
}

Class model::Person
{
  firstName: String[1];
  lastName: String[1];
}


###Mapping
Mapping model::NewMapping
(
  *model::Firm: Relational
  {
    ~primaryKey
    (
      [model::Test]FirmTable.id
    )
    ~mainTable [model::Test]FirmTable
    employees[model_Person]: [model::Test]@FirmPerson
  }
  *model::Person: Relational
  {
    ~filter [model::Test]AboveThirty
    ~primaryKey
    (
      [model::Test]PersonTable.id
    )
    ~mainTable [model::Test]PersonTable
    firstName: [model::Test]PersonTable.firstName,
    lastName: [model::Test]PersonTable.lastName
  }
)
```

**Comment by kshradhan** [comment]
- [X] Move InstanceSetImplementationSourceExplorer out to a separate file
- [ ] Refactor so for each subtype of InstanceSetImplementationState, we have a corresponding InstanceSetImplementationEditor, right now we start having too many instanceof logic in this component which is only getting worse
- [ ]  Add support for relational filter in form mode as well

**Comment by akphi** [comment]
@kshradhan feel free to move this check-list to your PR!
