### ISSUE TITLE
RFC: Add graph support for ServiceStore

### ISSUE THREAD

**Issue by gayathrir11** [finos/legend-studio#549]
### Implementation Plan

- [ ] Add text mode support for ServiceStore
- [ ] Add extension mechanism for ClassMapping
- [ ] Add text mode support for ServiceStoreClassMapping
- [ ] Add text mode support for ServiceStoreConnection

**Comment by akphi** [comment]
@gayathrir11 Could you add some context about what `ServiceStore` is?

**Comment by akphi** [comment]
**NOTE**: Updated this to `New Feature` instead of `RFC`
