### ISSUE TITLE
RFC: Rework release workflow

### ISSUE THREAD

**Issue by akphi** [finos/legend-studio#590]
### Overview

Right now, in our current release workflow, we have a need to create `progress/ad-hoc` feature releases. These could happen anytime (depending on demands) and quite frequently in the spirit of CI/CD. However, this clashes with our attempt to maintain a relatively fixed release cycle that is tracked by `milestone`. So we need to come up with a different release workflow. Now, we will come up with 3 types of releases:
- `standard release`: abide by the milestone, having a fixed release cycle - `major` bump
- `iteration release`: happens anytime on the default branch - `minor` bump
- `recovery release`: happens only after a `standard release` to provides essential bug fixes for a past standard release, **not iteration releases** - `patch` bump

### Implementation plan

- [ ] `GITHUB ACTION` Prepare Next Release Cycle (Manual): auto use `major` as bump type, omit the the create bump type patch
- [ ] `GITHUB ACTION` Bump Release Version (Manual) - Always bump a `major` and add file `.changeset/new-release.md`, renaming this PR to `Prepare New Release`
- [ ] Improve `release.yml`
  - [ ] Update so that for `Release` action: in the versioning step, we will always create a file `.changeset/new-iteration.md` if we're targetting `master` prior to calling `changeset version`
  - [ ] Fix the `Create Github release` script so if it's not a `standard release`, no Github release will be created (using `semver` and check if `minor(version) === 0 && patch(version) === 0`).
  - [ ] Create a script to output the name of the `New Release PR` and make that output available so it can be consumed in the pipeline
```
Iteration Release v2.3.0
Release v2.0.0
Recoverty Release v2.0.1
```
- [ ] `ADMIN` We should start doing `semver` for all the libraries
- [ ] `ADMIN` We move all things under 1 milestone (1.0.0)
- [ ] `DOC` Write doc to explain that libraries follow `semver`, but application follow a different convention `{release}.{iteration}.{recovery}`, so we have `standard release`, `iteration release`, `recovery release`
- [ ] `DOC` Write doc to say: Major bump is stable release cycle, minor bump is when we need to do ad-hoc release on default branch, patch release only for major release (so there is not such thing as `2.3.1`, there are only `2.3.0`, `2.4.0` and `2.0.1`, `2.0.2`)
