### ISSUE TITLE
Feature Request: `DataSpace` Enterprise view (MVP)

### ISSUE THREAD

**Issue by akphi** [finos/legend-studio#617]
### Overview

Enterprise view is a curated area to show dataspaces organized in a taxonomy tree to let users navigate concepts. We will make use of the `meta::pure::profiles::enterprise profile` tag, introduced in https://github.com/finos/legend-pure/pull/354

The general idea is to tag data spaces with `meta::pure::profiles::enterprise profile.taxonomyNodes` where the value can be comma-separated list of `taxonomy` path. In `enterprise` model explorer view, we will index all found data spaces with the mentioned tagged value to build a taxonomy tree

### Implementation plan

- [x] Add placeholder tabs for DataSpace viewer - show `Work in Progress` in the content - Done in https://github.com/finos/legend-studio/pull/639
  - [x] Entitlement/Authorization
  - [x] Test Data
  - [x] A tab to navigate to the project of the dataspace + the project the data space targets - this relies on https://github.com/finos/legend-studio/issues/638
- [x] Add enterprise view for dataspace
  - [x] Fetch dataspaces and organize them, extract taxonomy information from tagged value `meta::pure::profiles::enterprise profile.taxonomyNodes`
  - [x] Build and render taxonomy tree
  - [x] Genericize `DataSpaceViewer` and `DataSpaceViewerState` to be reused in enterprise model explorer. 
  - [x] Panel view for taxonomy node's dataspaces
  - [x] Show the dataspace counts for each node
  - [x] Navigate to taxonomy node using URL path params
  - [x] Navigate to taxonomy node and dataspace using URL path params

### Additional context

For a better context on `DSL DataSpace`, see #469
