### ISSUE TITLE
Feature request: Tagging mechanism for query

### ISSUE THREAD

**Issue by akphi** [finos/legend-studio#633]
### Similar requests

- [X] I have searched and found no existing similar requests

### What problems are you trying to solve?

In order for the created queries to be used in various systems, we should allow a generic extension mechanism like tagging. This could be used for things like `dataspace` where the query is created from, etc.

### Describe the solution you would like to see implemented

The reason why I brought up [DataSpace](#469) is that this could be seen as a very useful real use case. Let's say we have the following

```jsonc
// inside a query model
"tags": [
  {
    "tag": "dataspace",
    "value" : "model::test::dataSpace::TestDataSpace, legend.org.finos.test.example-project:latest"
  }
  // OR (splitting into 2 tags)
  {
    "tag": "dataspace",
    "value" : "model::test::dataSpace::TestDataSpace"
  },
  {
    "tag": "dataspaceProject",
    "value" : "legend.org.finos.test.example-project:latest"
  }
]

```

This is useful enough to trace out which data space has been used to create the query. And so we can expose an API when searching for queries to find all queries being created from a particular dataspace.

There could be other use cases for tagging queries, e.g. if the query is used in another system X, X needs to associate a query with some ID, tagging would be useful there.

```jsonc
// inside a query model
"tags": [
  {
    "tag": "systemXID",
    "value" : "asko12394aasd-123sad-123"
  }
]
```

So really, the solution is to extend the current query model to include a new field `tags: string[]`. The work for this would need to be done in both https://github.com/finos/legend-engine and https://github.com/finos/legend-studio

**Note that we should be consistent and use `TaggedValue` and `Stereotype` shapes. Note that we don't want to process these, because they could include external profiles/tags from systems, e.g. `systemXID` above**

### Implementation Plan

- [x] https://github.com/finos/legend-engine/pull/453
- [x] Add support for tagged value and stereotype for `Query`
- [x] Populate dataspace tag value when creating queries using dataspace

### Describe alternatives you have considered

I started this out thinking solely about `DataSpace` use case, but then I realize there are 2 shortcomings to having a dedicated structure in `Query` model for dataspace

1. It has to be a generic structure anyway, something like:

```
abstract class AbstractCreationContext {}

class DataSpaceCreationContext extends AbstractCreationContext {
  ...
}

class Query {
  ...
  creationContext: AbstractCreationContext;
}
```

This is fine, but it will make the structure harder to be dealt with as we have to mess with the extension mechanism in `Engine`. Though this extension mechanism will need to be done on `Studio` side though.

2. The proposed approach is too specific, for other use cases like mentioned above, such as associating the query with some ID of other systems, we would need some kind of generic string tags anyway. `string` is a must since there is no way for other systems to control some structured tag in our system.

### Contribution

- [ ] I would like to work on this feature
