### ISSUE TITLE
Dependencies Watchman

### ISSUE THREAD

**Issue by akphi** [finos/legend-studio#83]
## Dependency upgrades/bug-fixes to track

This list keeps track of dependencies that are either unstable or blockers to development in our project. Since unstable dependencies are usually marked with tag `@next`, or currently in `alpha`, `beta` channels, which can be ignored by `dependabot`. **For now, we want to have this pinned issue as the watchman, eventually, we should split it into smaller issues**

- [x] [@pmmmwh/react-refresh-webpack-plugin](https://github.com/pmmmwh/react-refresh-webpack-plugin): Using `beta` version. Part of `webpack@5` upgrade. (Resolved in https://github.com/finos/legend-studio/pull/495)
- [x] [webpack-dev-server](https://github.com/webpack/webpack-dev-server) Using `beta` version. Part of `webpack@5` upgrade (Resolved in https://github.com/finos/legend-studio/pull/422)
- [ ] [babel](https://github.com/babel/babel): In `babel@8`, a lot of configurations are to be set to default, we should keep track of these to slim down our babel preset.
- [ ] [jest](https://github.com/facebook/jest): Jest does not fully support ESM - See https://github.com/facebook/jest/issues/9430
  - [x] `Jest@27` will use `jest-circus` by default so we don't need to manually specify this like right now.
  - [x] Upgrade to `Jest@27` is currently being blocked due to `@types/jest` not being upgraded. This is causing a weird error: `The inferred type of ... cannot be named without a reference to 'jest/node_modules/pretty-format/build/types'`. Also, we should wait out a little bit as we need to confirm `Jest@27` works well with `testing-library`
- [ ] [yarn/berry](https://github.com/yarnpkg/berry):
  - [ ] https://github.com/finos/legend-studio/issues/501
  - [x] `yarn workspaces foreach` does not support `--skip-missing` flag, so if a workspace does not have a script with name specified, it will error out when we try to run such script on all workspaces (unlike `lerna`). See https://github.com/yarnpkg/berry/issues/62
- [ ] https://github.com/finos/legend-studio/issues/500
- [x] [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import) Wait for the fix for `no-extraneous-dependencies` in https://github.com/benmosher/eslint-plugin-import/pull/2121 to be published and enable that rule
- [x] [husky](https://github.com/typicode/husky): `husky@5` forces us to change our license. We have to wait till the [early-access phase is over](https://github.com/typicode/husky/issues/857).

## Dependency features to try out

This list keeps track of nice dependency features that are already supported in the versions we have, but we haven't quite had the time and effort to apply.

- [x] ~~[yarn/berry](https://github.com/yarnpkg/berry): [PnP](https://yarnpkg.com/features/pnp) is nice to try out but currently does not support ESM so we have to use `node_modules` as node linker mechanism. See https://github.com/yarnpkg/berry/issues/638~~
- [x] ~~[mobx](https://github.com/mobxjs/mobx): Use `override` for `computed` properties where appropriate (i.e. when both super class and sub class have concrete `methods/getters`)~~ - this will be enforced and checked by `mobx` automatically. The last thing we need to do is to stop using `super.` in `@computed`
- [x] [mobx](https://github.com/mobxjs/mobx): Use `flow` annotation with `makeObservable` and `flowResult` instead of wrapper `flow(function * ...)` - Check out [doc](https://mobx.js.org/actions.html#using-flow-instead-of-async--await-)
- [x] [typescript](https://github.com/microsoft/TypeScript): `typescript@4.3` supports for the `override` [syntax](https://devblogs.microsoft.com/typescript/announcing-typescript-4-3/#override). This is [currently blocked](https://github.com/prettier/prettier/pull/10959) by `prettier` (https://github.com/finos/legend-studio/pull/244)

**Comment by akphi** [comment]
W have upgraded `husky@6` and add a new step to `setup` script to install git hooks manually.

**Comment by akphi** [comment]
We have upgraded to `Typescript@4.3`, we need to try out the support for the `override` [syntax](https://devblogs.microsoft.com/typescript/announcing-typescript-4-3/#override). This is [currently blocked](https://github.com/prettier/prettier/pull/10959) by `prettier`

**Comment by akphi** [comment]
- [ ] [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import) Wait for the fix for `no-extraneous-dependencies` in https://github.com/benmosher/eslint-plugin-import/pull/2121 to be published and enable that rule
