### ISSUE TITLE
Feature request: Remove support for multiple SDLC instances

### ISSUE THREAD

**Issue by akphi** [finos/legend-studio#935]
### Similar requests

- [X] I have searched and found no existing similar requests

### How are you using Studio?

Legend Studio

### What problems are you trying to solve?

We decided that the overall use case for multiple SDLC instances have a few drawbacks:
1. It's generally confusing in the UI to indicate this, especially it obfuscates the URL. Generally, we are quite conservative about URL patterns in our app
2. The code logic to support this is unnecessarily complicated.
3.  **BONUS** If we remove URL patterns setup used to support this feature, #688 would be much easier.

Hence, we decided to remove the support for it. We basically undo the work of #642 and #149

#### Tasks

- [x] Remove the code logic
- [x] Write docs about this (potentially)

#### For migration/backward compatibility

- [x] Either modularize the `NotFound` page behavior so for existing infrastructure or we could rely on the doc config provided to make decision whether or not the show the `NotFound` page
- [x] For existing infrastructure that deploys Studio with multiple SDLC instances, add new deployment of /studio at routes like `/gcp-cloud-sdlc-studio/`, `/onprem-sdlc-studio/`, `aws-sdlc-studio/`, etc. We can also make use of the existing `studio.config.js` file with tweak to change `baseUrl` based on an environment variable to create specific deployment artifacts
- [x] Refactor the path for `viewer mode with GAV` to `view/archive/...`

#### Extra 

- [x] rework `taxonomy` app support for multiple taxonomy tree support in https://github.com/finos/legend-studio/pull/692 i.e. `/taxonomy/tree/.../...`

### Contribution

- [X] I would like to work on this feature
